spring:
  datasource:
    hikari:
      maximum-pool-size: 2000
    url: jdbc:mysql://116.196.104.38:3306/xsy?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
    username: ruguiniao
    password: 1qaz@WSX?
    driverClassName: com.mysql.jdbc.Driver

  redis:
    host: 116.196.104.38
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 116.196.112.85
    port: 5672
    username: ruguiniao
    password: 1qaz@WSX?
  thymeleaf:
    cache: false
    mode: HTML

mybatis:
  mapperLocations: classpath*:mappers/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
jwt:
  header: Authorization
  expiration: 3600 # 5 minutes
  secret: bird
  tokenHead: "Bearer "

server:
  port: 9000


